FROM nginx

CMD ["nginx"]

# COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
# RUN apt-get -y update && apt-get install -y php-cli php-zip unzip
# RUN cd /var/www/static/pinhole.tom-callahan.com/support
# RUN composer require phpmailer/phpmailer

EXPOSE 80
